// Generated by gencpp from file custom_msg_ros1/CustomMessage.msg
// DO NOT EDIT!


#ifndef CUSTOM_MSG_ROS1_MESSAGE_CUSTOMMESSAGE_H
#define CUSTOM_MSG_ROS1_MESSAGE_CUSTOMMESSAGE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_msg_ros1
{
template <class ContainerAllocator>
struct CustomMessage_
{
  typedef CustomMessage_<ContainerAllocator> Type;

  CustomMessage_()
    : custom_value(0.0)  {
    }
  CustomMessage_(const ContainerAllocator& _alloc)
    : custom_value(0.0)  {
  (void)_alloc;
    }



   typedef double _custom_value_type;
  _custom_value_type custom_value;





  typedef boost::shared_ptr< ::custom_msg_ros1::CustomMessage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_msg_ros1::CustomMessage_<ContainerAllocator> const> ConstPtr;

}; // struct CustomMessage_

typedef ::custom_msg_ros1::CustomMessage_<std::allocator<void> > CustomMessage;

typedef boost::shared_ptr< ::custom_msg_ros1::CustomMessage > CustomMessagePtr;
typedef boost::shared_ptr< ::custom_msg_ros1::CustomMessage const> CustomMessageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_msg_ros1::CustomMessage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_msg_ros1::CustomMessage_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::custom_msg_ros1::CustomMessage_<ContainerAllocator1> & lhs, const ::custom_msg_ros1::CustomMessage_<ContainerAllocator2> & rhs)
{
  return lhs.custom_value == rhs.custom_value;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::custom_msg_ros1::CustomMessage_<ContainerAllocator1> & lhs, const ::custom_msg_ros1::CustomMessage_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace custom_msg_ros1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::custom_msg_ros1::CustomMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_msg_ros1::CustomMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msg_ros1::CustomMessage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_msg_ros1::CustomMessage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msg_ros1::CustomMessage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_msg_ros1::CustomMessage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_msg_ros1::CustomMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9636d3d3e4d6ad9498c0e9356fecdcaa";
  }

  static const char* value(const ::custom_msg_ros1::CustomMessage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9636d3d3e4d6ad94ULL;
  static const uint64_t static_value2 = 0x98c0e9356fecdcaaULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_msg_ros1::CustomMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_msg_ros1/CustomMessage";
  }

  static const char* value(const ::custom_msg_ros1::CustomMessage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_msg_ros1::CustomMessage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 custom_value\n"
;
  }

  static const char* value(const ::custom_msg_ros1::CustomMessage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_msg_ros1::CustomMessage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.custom_value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CustomMessage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_msg_ros1::CustomMessage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_msg_ros1::CustomMessage_<ContainerAllocator>& v)
  {
    s << indent << "custom_value: ";
    Printer<double>::stream(s, indent + "  ", v.custom_value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MSG_ROS1_MESSAGE_CUSTOMMESSAGE_H
